### ISSUE TITLE
Build FFI by default in quickstart Stack setup

### ISSUE THREAD

**Issue by oubiwann** [haskell-lisp/husk-quick-start#1]
Not sure how to do this yet ...

**Comment by justinethier** [comment]
Here is some background information, if it helps. From http://justinethier.github.io/husk-scheme/manual/ffi.html

> To enable the FFI just pass the option <b>-fuseffi</b> to cabal when installing or upgrading Husk.

So I think you would want to run a command such as the following to include the FFI:

```
cabal install -fuseffi
```

By the way, thanks for putting together this quick start.

**Comment by oubiwann** [comment]
You're very welcome! I've been wanting to do this for a couple of years -- I'm glad I'm finally getting around to it :-)

For `stack` I needed to add this to the `stack.yaml` file:

``` yaml
flags:
  husk-scheme:
    useffi: true   
```

But ... that resulted in a compile error. I'll try it again with:
- just cabal
- the same version of husk-scheme
- the latest version of husk-scheme

If it's still an issue, I'll submit a ticket ...

**Comment by oubiwann** [comment]
I'm running on both Mac OS X and Ubuntu. On Mac, everything worked fine (did that earlier this afternoon). Tonight, the Ubuntu install failed. In particular, it seems that the terminfo install is failing due to a lack of one or more of the following:
- hmake
- jhc
- lhc
- lhc-pkg
- nhc98
- uhc

@justinethier  This may simply be due to my system not being properly configured ... I'll open some tickets and maybe you can set me straight :-)

**Comment by oubiwann** [comment]
I confirmed that Mac and Linux both build vanilla husk 3.19.2 without `-fuseffi`. However, with that option they fail (looks like  a function sig has changed?).

I've opened a ticket here:
- https://github.com/justinethier/husk-scheme/issues/209

_Update_: And there's already a fix! Woo-hoo!

(Now to figure out how to get Stack to install deps from a github repo ...)

**Comment by oubiwann** [comment]
Okay! Fix is in place and tested with `useffi` flag in the stack yaml file.
